---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg-svc
spec:
  ports:
    - name: gotenberg
      port: 80
      targetPort: gotenberg
      protocol: TCP
  sessionAffinity: None
  clusterIP: None
