---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: app
          image: "ghcr.io/paperless-ngx/paperless-ngx:1.16"
          imagePullPolicy: Always
          env:
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-db-secret
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: "app-config"
            - configMapRef:
                name: "db-sentinel"
            - configMapRef:
                name: "db-connect"
            - configMapRef:
                name: "app-sentinel"
            - secretRef:
                name: "paperless-app-secret"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /usr/src/paperless/data
            - name: media
              mountPath: /usr/src/paperless/media
            - name: export
              mountPath: /usr/src/paperless/export
            - name: consume
              mountPath: /usr/src/paperless/consume
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: export
          persistentVolumeClaim:
            claimName: export-pvc
        - name: consume
          hostPath:
            path: /mnt/docs/paperless-consume
            type: Directory
        - name: media
          hostPath:
            path: /mnt/docs/paperless
            type: Directory
